#!/usr/bin/env python3
"""
update_ontology_lock.py — Regenerate ontology lock file with SHA-256 hashes.

Source: Microsoft S4 Workspace Deliverable — April 2026 Pantheon Council Session
Doctrine: D-89 Ontology Lock Protocol
Purpose: Generates SHA-256 hashes for all ontology-defining files (manifest.yaml,
         registry YAML, 12x12 matrix) to detect unauthorized structural changes.

Usage:
    python toolchain/update_ontology_lock.py                    # Update lock file
    python toolchain/update_ontology_lock.py --verify-only      # Verify without updating
    python toolchain/update_ontology_lock.py --output FILE      # Write to custom path
"""

import hashlib
import os
import sys
import argparse
from pathlib import Path


REPO_ROOT = Path(__file__).parent.parent
LOCK_FILE = REPO_ROOT / "toolchain" / "ontology_lock.sha256"

# Files that define the ontology structure — changes to these require protocol compliance
ONTOLOGY_PATTERNS = [
    "houses/*/S*/manifest.yaml",
    "registries/module_registry.yaml",
    "registries/doctrine_registry.yaml",
    "registries/invariant_registry.yaml",
    "registries/12x12_matrix.yaml",
    "registries/lattice_ontology.yaml",
    "element-145/boot_manifest.yaml",
]


def sha256_file(filepath: Path) -> str:
    """Compute SHA-256 hash of a file."""
    h = hashlib.sha256()
    with open(filepath, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def collect_ontology_files() -> list[tuple[str, Path]]:
    """Collect all ontology-defining files matching the patterns."""
    import glob
    files = []
    for pattern in ONTOLOGY_PATTERNS:
        matches = sorted(glob.glob(str(REPO_ROOT / pattern)))
        for m in matches:
            relpath = os.path.relpath(m, REPO_ROOT)
            files.append((relpath, Path(m)))
    return files


def generate_lock_content() -> str:
    """Generate the lock file content with SHA-256 hashes."""
    files = collect_ontology_files()
    lines = []
    lines.append(f"# Ontology Lock File — D-89 Ontology Lock Protocol")
    lines.append(f"# Generated by toolchain/update_ontology_lock.py")
    lines.append(f"# {len(files)} ontology-defining files tracked")
    lines.append(f"# Any change to these files requires D-89 protocol compliance")
    lines.append("")
    for relpath, filepath in files:
        h = sha256_file(filepath)
        lines.append(f"{h}  {relpath}")
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="D-89 Ontology Lock Protocol — SHA-256 hash management")
    parser.add_argument("--verify-only", action="store_true", help="Verify current lock file without updating")
    parser.add_argument("--output", type=str, default=None, help="Write lock file to custom path")
    args = parser.parse_args()

    content = generate_lock_content()

    if args.output:
        output_path = Path(args.output)
        output_path.write_text(content)
        print(f"Lock file written to {output_path}")
        return

    if args.verify_only:
        if not LOCK_FILE.exists():
            print("ERROR: Lock file does not exist. Run without --verify-only to generate.")
            sys.exit(1)
        existing = LOCK_FILE.read_text()
        if existing.strip() == content.strip():
            print("✓ Ontology lock verification passed — D-89 compliant")
        else:
            print("ERROR: Ontology lock mismatch detected.")
            print("The ontology structure has changed without lock file update.")
            print("Run 'python toolchain/update_ontology_lock.py' to regenerate.")
            sys.exit(1)
        return

    # Default: update lock file
    LOCK_FILE.write_text(content)
    files = collect_ontology_files()
    print(f"✓ Ontology lock file updated — {len(files)} files tracked")
    print(f"  Written to: {LOCK_FILE}")


if __name__ == "__main__":
    main()
